Introduction
-----------

Welcome to the Absolute Beginners guide to OpenShift for the Impatient. 

Who you are:
~~~~~~~~~~~~

As the title indicates, we are assuming little in the way of background knowledge except:

* Know how to create a web application
* Know how to use the command line
* You can program in one of the six programming languages OpenShift supports
* You can use a text editor on a Linux machine, the most basic is http://www.nano-editor.org/docs.php[nano] but VI or Emacs will be okay as well

This guide is intended for programmers who want to get started using OpenShift as quickly as possible but also want to understand a slight bit of what they are doing.  

Goal of this document:
~~~~~~~~~~~~~~~~~~~~~~

We want to enable you to be self sufficient in the basic use of Openshift for creating and hosting your web applications in as little text as possible. Therefore, we will not go in to long explanations of technology used in OpenShift or different programming paradigms but instead give you links where you can go to read more.


About this Document:
~~~~~~~~~~~~~~~~~~~~

This document is released under http://creativecommons.org/licenses/by/3.0/[Creative Commons License 3 Unported] which allows you to do almost anything you want with this as long as you attribute the original doc back to this site.

The source is available on Github at the following location: https://github.com/thesteve0/osbeginnerguide 
// this will change once we pick a better place.

Everyone is invited to help contribute and improve the document. Sole responbility about what goes in the original github site belongs to the OpenShift team for now. That said, we encourage debate and discussion on the flow and direction of the document.

The document is written in http://www.methods.co.nz/asciidoc/index.html[AsciiDoc], a simpler format than DocBook but with all the ability to output to multiple formats. The best reference is the http://www.methods.co.nz/asciidoc/userguide.html[AsciiDoc User Guide], but there are some guides avaiable http://asciidoctor.org/docs/asciidoc-writers-guide/#writing-in-asciidoc-first-steps[here], https://github.com/jakoch/asciidoc-cheatsheet[here], and http://www.methods.co.nz/asciidoc/book-multi.html[here]. Given the ability of Github to render AsciiDoc, this format also seemed a natural choice for the tutorial. 

// Who you are
//	What the goal is
//	Where to make this doc better
//		GitHub
//		ASCIIDoc 
